---
title: 'SWEpy: a python library for quick and easy access to brightness temperature data for SWE analysis'
tags:
  - Python
  - snow
  - swe
  - data after_success
  - data processing
authors:
  - name: William M. Norris
    orcid: 0000-0002-6772-9600
    affiliation: 1
  - name: Carson J. Farmer
    orcid: 0000-0000-0000-0000
    affiliation: 1
affiliations:
 - name: University of Colorado Boulder
   index: 1
date: 4 September 2018
---

# Summary

Modern analysis of earth’s systems requires significant volumes of increasingly fine resolution spatial and temporal information. For example, the MEaSUREs calibrated enhanced temperature brightness (CETB) data set, released by the National Snow and Ice Data Center (NSIDC), is no exception (Brodzik, 2016). The MEaSUREs dataset contains twice daily passive microwave imagery from 1978 through 2017, which can be particularly useful for spatial-temporal analysis of snow water equivalent (SWE). In addition to high temporal resolution, the MEaSUREs CETB dataset contains imagery that has been resampled from 25km down to 6.25km wide pixels, allowing for analysis to be done at a finer spatial scale than previously available versions of the data source. While this data is exceedingly useful, it can take considerable time to set up scripts for web access, geographic subsetting, and merging sequential images into useful time cubes. The MEaSUREs data set is also large: accessing a full time series of Northern Hemisphere imagery would require easily a terabyte of disc space, which most researchers do not have available on their local computer. SWEpy was developed in part to deal with these issues, while also providing basic data manipulation tools to facilitate SWE-based research. SWEpy is a Python library that allows for quick and easy web-access, geographic subsetting, and concatenation of MEaSUREs CETB files. The primary goal of SWEpy is to reduce the time needed for researchers to access and begin making use of MEaSUREs CETB data. A user with very little knowledge of Python can use SWEpy to access this data within minutes, and those more familiar with the scientific Python ecosystem can benefit from the wealth of tools available for subsequent analysis of CETB data.
Ease of use is a primary goal for SWEpy. Users can enter as little information as a date range, bounding coordinates, and their Earthdata login credentials, and SWEpy will return two single time cube files with only the data for the user’s study area included. SWEpy has intelligent defaults pre-defined for various CETB files used in SWE analysis,such as which sensor is the most stable for a given year, as well as more specific web-access functionality. Additionally, in order to avoid running out of disk space, SWEpy will optimize long running data access sessions by automating the whole process, stopping to subset and concatenate files incrementally when the entire dataset will be too large to store on disk.
SWEpy is available from GitHub (https://github.com/wino6687/SWEpy) and anaconda (https://anaconda.org/wino6687/swepy). Full documentation can be found in the GitHub repository wiki (https://github.com/wino6687/SWEpy/wiki). Any issues or bugs can be reported to the issues page on the GitHub repository:  https://github.com/wino6687/SWEpy/issues.



# References
Example paper.bib file:

@article{Pearson:2017,
    Adsnote = {Provided by the SAO/NASA Astrophysics Data System},
    Adsurl = {http://adsabs.harvard.edu/abs/2017arXiv170304627P},
    Archiveprefix = {arXiv},
    Author = {{Pearson}, S. and {Price-Whelan}, A.~M. and {Johnston}, K.~V.},
    Eprint = {1703.04627},
    Journal = {ArXiv e-prints},
    Keywords = {Astrophysics - Astrophysics of Galaxies},
    Month = mar,
    Title = {{Gaps in Globular Cluster Streams: Pal 5 and the Galactic Bar}},
    Year = 2017
}

@book{Binney:2008,
    Adsnote = {Provided by the SAO/NASA Astrophysics Data System},
    Adsurl = {http://adsabs.harvard.edu/abs/2008gady.book.....B},
    Author = {{Binney}, J. and {Tremaine}, S.},
    Booktitle = {Galactic Dynamics: Second Edition, by James Binney and Scott Tremaine.~ISBN 978-0-691-13026-2 (HB).~Published by Princeton University Press, Princeton, NJ USA, 2008.},
    Publisher = {Princeton University Press},
    Title = {{Galactic Dynamics: Second Edition}},
    Year = 2008
}

@article{zenodo,
    Abstractnote = {Gala is a Python package for Galactic astronomy and gravitational dynamics. The bulk of the package centers around implementations of gravitational potentials, numerical integration, and nonlinear dynamics.},
    Author = {Adrian Price-Whelan and Brigitta Sipocz and Syrtis Major and Semyeong Oh},
    Date-Modified = {2017-08-13 14:14:18 +0000},
    Doi = {10.5281/zenodo.833339},
    Month = {Jul},
    Publisher = {Zenodo},
    Title = {adrn/gala: v0.2.1},
    Year = {2017},
    Bdsk-Url-1 = {http://dx.doi.org/10.5281/zenodo.833339}
}

@article{gaia,
    author = {{Gaia Collaboration}},
    title = "{The Gaia mission}",
    journal = {\aap},
    archivePrefix = "arXiv",
    eprint = {1609.04153},
    primaryClass = "astro-ph.IM",
    keywords = {space vehicles: instruments, Galaxy: structure, astrometry, parallaxes, proper motions, telescopes},
    year = 2016,
    month = nov,
    volume = 595,
    doi = {10.1051/0004-6361/201629272},
    adsurl = {http://adsabs.harvard.edu/abs/2016A%26A...595A...1G},
}

@article{astropy,
    author = {{Astropy Collaboration}},
    title = "{Astropy: A community Python package for astronomy}",
    journal = {\aap},
    archivePrefix = "arXiv",
    eprint = {1307.6212},
    primaryClass = "astro-ph.IM",
    keywords = {methods: data analysis, methods: miscellaneous, virtual observatory tools},
    year = 2013,
    month = oct,
    volume = 558,
    doi = {10.1051/0004-6361/201322068},
    adsurl = {http://adsabs.harvard.edu/abs/2013A%26A...558A..33A}
}
